import {POST_ENTRY_START,
    POST_ENTRY_SUCCESS,
    POST_ENTRY_FAIL,
    FETCH_ENTRY_START,
    FETCH_ENTRY_SUCCESS,
    FETCH_ENTRY_FAIL,
    PUT_ENTRY_START,
    PUT_ENTRY_SUCCESS,
    PUT_ENTRY_FAIL,
    DELETE_ENTRY_START,
    DELETE_ENTRY_SUCCESS,
    DELETE_ENTRY_FAIL
} from "../actions/entryActions"

